version: '3'


services:
  bookstore_postgresql:
    image: postgres:12
    container_name: bookstore_postgresql
    volumes:
      - bookstore_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - bookstore_network
volumes:
  bookstore_postgresql:
    external: true
networks:
  bookstore_network:
    external: true
