# Generated by Django 3.2 on 2021-05-31 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('Item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
            options={
                'ordering': ['-Item__price'],
            },
        ),
    ]
