# Generated by Django 3.2 on 2021-05-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210531_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image1',
            new_name='imageslide',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image2',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
