# Generated by Django 3.2 on 2021-06-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='topic',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='آدرس دسته بندی'),
        ),
    ]
