# Generated by Django 3.2 on 2021-06-04 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210604_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shopping_address',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_addresses', to='core.address'),
        ),
    ]
