# Generated by Django 3.2 on 2021-06-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس آی پی')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__id'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی ها'},
        ),
        migrations.AddField(
            model_name='book',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='core.IPAddress', verbose_name='بازدیدها'),
        ),
    ]
