# Generated by Django 3.2 on 2021-06-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210616_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی ها'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='icone',
            new_name='icon',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('B', 'صورت حساب'), ('S', 'خریدکردن')], max_length=1, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='address',
            name='apartment_address',
            field=models.CharField(max_length=250, verbose_name='آدرس آپارتمان'),
        ),
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False, verbose_name='پیشفرض'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(choices=[('B', 'صورت حساب'), ('S', 'خریدکردن')], max_length=250, verbose_name='آدرس خیابان'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=200, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='core.Category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='book',
            name='discount_price',
            field=models.FloatField(blank=True, null=True, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='book',
            name='imageslide',
            field=models.ImageField(blank=True, null=True, upload_to='book', verbose_name='اسلاید تصویر'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد صفحات'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(verbose_name='قیمت کتاب'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishers',
            field=models.CharField(blank=True, max_length=100, verbose_name='ناشر'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='special_offer',
            field=models.BooleanField(default=False, verbose_name='پیشنهاد ویژه'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=10, verbose_name='عنوان کتاب'),
        ),
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مترجم'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(blank=True, verbose_name='سال انتشار'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=20, verbose_name='کد کوپن'),
        ),
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.IntegerField(max_length=15, verbose_name='تماس'),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=40, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=30, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='message',
            name='password1',
            field=models.CharField(max_length=40, verbose_name='رمز عبور'),
        ),
        migrations.AlterField(
            model_name='message',
            name='password2',
            field=models.CharField(max_length=40, verbose_name='تکرار رمز عبور'),
        ),
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.CharField(max_length=30, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='being_delivered',
            field=models.BooleanField(default=False, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_addresses', to='core.address', verbose_name='آدرس صدور صورتحساب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(to='core.OrderBook', verbose_name='کتاب ها'),
        ),
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coupon', verbose_name='کوپن'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(verbose_name='زمان ثبت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.payment', verbose_name='پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='received',
            field=models.BooleanField(default=False, verbose_name='وضعیت تحویل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد مرجوعی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_granted',
            field=models.BooleanField(default=False, verbose_name='اعطا مرجوعی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_requested',
            field=models.BooleanField(default=False, verbose_name='درخواست مرجوعی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_addresses', to='core.address', verbose_name='آدرس محل ارسال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book', verbose_name='نام کتاب'),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='orderbook',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(verbose_name='جمع کل خرید'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='strip_charge_id',
            field=models.CharField(max_length=50, verbose_name='شناسه نوار هزینه'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='refund',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.TextField(verbose_name='دلیل'),
        ),
        migrations.AlterField(
            model_name='slidshow',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.book', verbose_name='نام کتاب'),
        ),
        migrations.AlterField(
            model_name='slidshow',
            name='status',
            field=models.BooleanField(default=False, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='one_click_purchasing',
            field=models.BooleanField(default=False, verbose_name='خرید با یک کلیک'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوار شناسه مشتری'),
        ),
    ]
