# Generated by Django 3.2 on 2021-06-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210618_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discount_price',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت نهایی'),
        ),
    ]
