# Generated by Django 3.2 on 2021-06-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_address_street_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('B', 'صورت حساب'), ('S', 'خریدکردن')], max_length=1, verbose_name='انتخاب آدرس'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='strip_charge_id',
            field=models.CharField(max_length=50, verbose_name='شناسه پرداخت'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='one_click_purchasing',
            field=models.BooleanField(default=False, verbose_name='خرید'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه مشتری'),
        ),
    ]
