# Generated by Django 3.2 on 2021-06-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210620_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.FloatField(blank=True, null=True, verbose_name='درصد تخفیف'),
        ),
    ]
