# Generated by Django 3.2 on 2021-06-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210622_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discount',
            field=models.FloatField(blank=True, null=True, verbose_name='قیمت نهایی'),
        ),
    ]
