# Generated by Django 3.2 on 2021-06-22 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_book_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='discount',
            new_name='discount_price',
        ),
    ]
