# Generated by Django 3.2.4 on 2021-06-24 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210622_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discount_percent',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.category', verbose_name='زیر دسته'),
        ),
    ]
