# Generated by Django 3.2.4 on 2021-06-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210624_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(default=1, max_length=100, verbose_name='مترجم'),
            preserve_default=False,
        ),
    ]
