# Generated by Django 3.2 on 2021-06-27 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_book_translator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی ها'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=200, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishers',
            field=models.CharField(blank=True, max_length=100, verbose_name='ناشر'),
        ),
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مترجم'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category', verbose_name='زیر دسته'),
        ),
    ]
