# Generated by Django 3.2 on 2021-06-27 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210627_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='imageslide',
        ),
    ]
