# Generated by Django 3.2 on 2021-06-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_book_imageslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(verbose_name='درصد تخفیف'),
        ),
    ]
