# Generated by Django 3.2 on 2021-06-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد سفارش'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(verbose_name='قیمت'),
        ),
    ]
