# Generated by Django 3.2 on 2021-06-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210630_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان کتاب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='being_delivered',
            field=models.CharField(choices=[('S', 'در صف بررسی'), ('C', 'تایید سفارش'), ('P', 'آماده سازی سفارش'), ('p', 'بسته بندی'), ('D', 'تحویل به پست'), ('c', 'تحویل مشتری'), ('R', 'مرجوعی')], default='S', max_length=1, verbose_name='وضعیت سفارش'),
        ),
    ]
